plugins {
  id 'eclipse'
  id 'java-library'
  id 'maven-publish'
  id 'idea'
  id 'me.shedaniel.unified-publishing' version '0.1.+'
  id 'net.neoforged.gradle.userdev' version '7.0.142'
}

base {
  group = maven_group
  version = mod_version
  archivesName = project.archives_base_name
}

java {
  toolchain.languageVersion = JavaLanguageVersion.of(21)
  withSourcesJar()
}

minecraft.accessTransformers.file rootProject.file("src/main/resources/META-INF/accesstransformer.cfg")

// Default run configurations.
// These can be tweaked, removed, or duplicated as needed.
runs {
  // applies to all the run configs below
  configureEach {
    // Recommended logging data for a userdev environment
    // The markers can be added/remove as needed separated by commas.
    // "SCAN": For mods scan.
    // "REGISTRIES": For firing of registry events.
    // "REGISTRYDUMP": For getting the contents of all registries.
    systemProperty 'forge.logging.markers', 'REGISTRIES'

    // Recommended logging level for the console
    // You can set various levels here.
    // Please read: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels
    systemProperty 'forge.logging.console.level', 'debug'

    modSource project.sourceSets.main
  }

  client {
    // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
    systemProperty 'forge.enabledGameTestNamespaces', project.modid
  }

  server {
    systemProperty 'forge.enabledGameTestNamespaces', project.modid
    programArgument '--nogui'
  }

  // This run config launches GameTestServer and runs all registered gametests, then exits.
  // By default, the server will crash when no gametests are provided.
  // The gametest system is also enabled by default for other run configs under the /test command.
  gameTestServer {
    systemProperty 'forge.enabledGameTestNamespaces', project.modid
  }

  data {
    // example of overriding the workingDirectory set in configureEach above, uncomment if you want to use it
    // workingDirectory project.file('run-data')

    // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
    programArguments.addAll '--mod', project.modid, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
  }
}

configurations {
  runtimeClasspath.extendsFrom localRuntime
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
  mavenCentral()
  maven { url = "https://repo.spongepowered.org/repository/maven-public/" }
  maven {
    name = "Custom Machinery maven"
    url = "https://maven.frinn.fr/repository/maven/"
    content {
      includeGroup "frinn.custommachinery"
    }
  }
  maven {
    name = "Mod maven"
    url = "https://modmaven.dev/"
    content {
      includeGroup "mcjty.theoneprobe"
      includeGroup "mekanism"
    }
  }
  maven {
    name = "Shedaniel maven"
    url = "https://maven.architectury.dev/"
    content {
      includeGroup "me.shedaniel.cloth"
    }
  }
  maven {
    name = "Lat's maven"
    url = "https://maven.saps.dev/releases"
    content {
      includeGroup "dev.latvian.mods"
      includeGroup "dev.latvian.apps"
    }
  }
  maven {
    // location of the maven that hosts JEI files
    name = "Progwml6 maven"
    url = "https://dvs1.progwml6.com/files/maven/"
    content {
      includeGroup "mezz.jei"
    }
  }
  maven {
    name = 'BlameJared Maven'
    url = 'https://maven.blamejared.com'
    content {
      includeGroup "com.blamejared.crafttweaker"
      includeGroup "org.openzen.zencode"
      includeGroup "mezz.jei"
      includeGroup "com.hollingsworth.ars_nouveau"
      includeGroup "vazkii.patchouli"
    }
  }
  maven {
    name = "Illusive Soulworks maven"
    url = "https://maven.theillusivec4.top/"
  }
  //Needed for KubeJS
  maven {
    name = "Jitpack Maven"
    url = "https://jitpack.io"
    content {
      includeGroup "com.github.rtyley"
    }
  }
  maven {
    name = 'Forge'
    url = "https://maven.minecraftforge.net"
  }
  maven {
    name = "OctoStudios"
    url = uri("https://maven.octo-studios.com/releases")
  }
  maven {
    name = 'GeckoLib'
    url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
    content {
      includeGroup("software.bernie.geckolib")
    }
  }
  maven {
    url "https://www.cursemaven.com"
    content {
      includeGroup "curse.maven"
    }
  }
  mavenLocal()
}

dependencies {
  // Specify the version of Minecraft to use.
  // Any artifact can be supplied so long as it has a "userdev" classifier artifact and is a compatible patcher artifact.
  // The "userdev" classifier will be requested and setup by ForgeGradle.
  // If the group id is "net.minecraft" and the artifact id is one of ["client", "server", "joined"],
  // then special handling is done to allow a setup of a vanilla dependency without the use of an external repository.
  implementation "net.neoforged:neoforge:${project.neo_version}"
  implementation ("io.github.llamalad7:mixinextras-neoforge:0.4.1")
  // ars
  localRuntime ("software.bernie.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}")
  localRuntime ("vazkii.patchouli:Patchouli:${project.minecraft_version}-${project.patchouli_version}")
  localRuntime "top.theillusivec4.curios:curios-neoforge:${project.curios_version}"
  localRuntime compileOnly ("com.hollingsworth.ars_nouveau:ars_nouveau-${project.minecraft_version}.0:${project.ars_version}.729") // TODO: fix minecraft version

  // JEI 10
  compileOnly ("mezz.jei:jei-${project.minecraft_version}.1-common-api:${project.jei_version}")
  compileOnly ("mezz.jei:jei-${project.minecraft_version}.1-neoforge-api:${project.jei_version}")
  localRuntime ("mezz.jei:jei-${project.minecraft_version}.1-neoforge:${project.jei_version}")

  // Custom Machinery
  localRuntime ("me.shedaniel.cloth:cloth-config-neoforge:${project.cloth_config_version}")
  localRuntime compileOnly ("frinn.custommachinery:CustomMachinery-neoforge:${project.minecraft_version}.1-${project.custommachinery_version}") // TODO: fix minecraft version

  //KubeJS
  localRuntime compileOnly ("dev.latvian.mods:kubejs-neoforge:${project.kubejs_version}")

  //Crafttweaker
  localRuntime compileOnly ("com.blamejared.crafttweaker:CraftTweaker-neoforge-${project.minecraft_version}.1:${project.ct_version}")

  // Jade
  localRuntime compileOnly("curse.maven:jade-324717:${jade_version}")

  // The one probe
  localRuntime compileOnly("mcjty.theoneprobe:theoneprobe:${top_version}") {transitive = false}

  // Mekanism
  localRuntime("mekanism:Mekanism:${mekanism_version}")
}

processResources {

  inputs.property "version", project.version

  filesMatching(['META-INF/mods.toml', 'pack.mcmeta', 'META-INF/neoforge.mods.toml']) {
    expand "modid": modid,
        "mod_version": mod_version,
        "mod_name": mod_name,
        "mod_description": mod_description,
        "author": author,
        "issues": issues,
        "license": license,
        "icon": icon,
        "minecraft_version": minecraft_version,
        "custommachinery_version": custommachinery_version,
        "ars_version": ars_version,
        "neo_version": neo_version
  }
}

tasks.withType(JavaCompile).configureEach {
  options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
  options.release = 21
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
  module {
    downloadSources = true
    downloadJavadoc = true
  }
}

unifiedPublishing {
  project {
    displayName = "Custom-Machinery-ArsNouveau-${project.minecraft_version}-${project.mod_version}"
    releaseType = "release"
    if(rootProject.file("CHANGELOG.md").exists()) {
      changelog = rootProject.file("CHANGELOG.md").text
    }
    gameVersions = ["1.21", "1.21.1"]
    gameLoaders = ["neoforge"]
    mainPublication jar

    var CURSE_API_KEY = System.getenv("CURSEFORGE_KEY")
    if (CURSE_API_KEY != null) {
      curseforge {
        token = CURSE_API_KEY
        id = "969074"
        gameVersions.addAll "Java 21"
        relations {
          depends "custom-machinery"
          depends "ars-nouveau"
          optional "crafttweaker"
          optional "kubejs"
        }
      }
    }
  }
}

// Prevent Mixin annotation processor from getting into IDEA's annotation processor settings
// Copied from Botania
if (System.getProperty("idea.sync.active") == "true") {
  afterEvaluate {
    tasks.withType(JavaCompile).all {
      it.options.annotationProcessorPath = files()
    }
  }
}
