org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
org.gradle.debug=false

archives_base_name=CustomMachineryArsNoveau
maven_group=es.degrassi

neogradle.subsystems.parchment.minecraftVersion=1.20.6
neogradle.subsystems.parchment.mappingsVersion=2024.05.01

minecraft_version=1.21
neo_version=21.1.32

modid=custommachineryars
mod_version=1.1.1
mod_name=Custom Machinery ArsNouveau
mod_description=Add ArsNouveau integration for Custom Machinery
author=Alec_016GG
homepage=https://www.curseforge.com/minecraft/mc-mods/custom-machinery-ars-nouveau
github=https://github.com/alec016/CM-ArsNouveau
issues=https://github.com/alec016/CM-ArsNouveau/issues
wiki=https://alec016.gitbook.io/custom-machinery-ars-1.19/
license=GNU Lesser General Public License v3.0
icon=icon.png

# Other mods
custommachinery_version=0.10.12
jei_version=19.14.1.144
kubejs_version=2101.7.0-build.153
cloth_config_version=15.0.130
ct_version=21.0.1
ars_version=5.1.0
geckolib_version=4.5.7
jade_version=5591256
top_version=1.21_neo-12.0.3-5
mekanism_version=1.21.1-10.7.5.62
patchouli_version=87-NEOFORGE-SNAPSHOT
curios_version=8.0.0-beta+1.21