org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
org.gradle.debug=false

archives_base_name=custom_machinery_ars
maven_group=es.degrassi

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

minecraft_version=1.21.1
neo_version=21.1.194

modid=custommachineryars
mod_version=1.2.0
mod_name=Custom Machinery ArsNouveau
mod_description=Add ArsNouveau integration for Custom Machinery
author=Alec_016GG
homepage=https://www.curseforge.com/minecraft/mc-mods/custom-machinery-ars-nouveau
github=https://github.com/alec016/CM-ArsNouveau
issues=https://github.com/alec016/CM-ArsNouveau/issues
wiki=https://alec016.gitbook.io/custom-machinery-ars-1.19/
license=GNU Lesser General Public License v3.0
icon=icon.png
mod_authors=Alec_016GG
mod_url=https://alec016.gitbook.io/custom-machinery-ars-1.19/
mod_github=https://github.com/alec016/CM-ArsNouveau
mod_issues=https://github.com/alec016/CM-ArsNouveau/issues
mod_license=GNU Lesser General Public License v3.0

# Other mods
custommachinery_version=0.10.44
jei_version=19.21.0.247
kubejs_version=2101.7.1-build.184
ct_version=21.0.27
jade_version=6291517
top_version=1.21_neo-12.0.4-6
mekanism_version=1.21.1-10.7.13.78
ars_version=5.10.4
geckolib_version=4.7.7
patchouli_version=92-NEOFORGE
curios_version=9.3.1+1.21
nuggets_version=1.0.7.38