modLoader = "javafml"
loaderVersion = "[47,)"
license = "${license}"
[[mods]] #mandatory
# The modid of the mod
modId = "custommachineryars" #mandatory
version = "1.0.1"
displayName = "Custom Machinery ArsNouveau"
logoFile = "icon.png"
description = '''
${mod_description}
'''

[[dependencies.custommachineryars]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.custommachineryars]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.custommachineryars]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"

[[dependencies.custommachineryars]]
modId = "custommachinery"
mandatory = true
versionRange = "[${custommachinery_version},)"
ordering = "AFTER"

[[dependencies.custommachineryars]]
modId = "ars_nouveau"
mandatory = true
versionRange = "[${ars_version},)"
ordering = "AFTER"
